//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApproveApi.Models.WebApvModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int regId { get; set; }
        public string schemaName { get; set; }
        public string Schema { get; set; }
        public string targetNameSpace { get; set; }
        public string Transform { get; set; }
    }
}
