//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApproveApi.Models.PersonnelModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string empId { get; set; }
        public string fNameTH { get; set; }
        public string sNameTH { get; set; }
        public string fNameEN { get; set; }
        public string sNameEN { get; set; }
        public string positionId { get; set; }
        public Nullable<int> prefixId { get; set; }
        public string companyId { get; set; }
    }
}
