//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApproveApi.Models.WebApvModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        public string subjectName { get; set; }
        public string dataRequest { get; set; }
        public Nullable<System.DateTime> dateRequest { get; set; }
        public string empId { get; set; }
        public string statusId { get; set; }
        public int docDetailId { get; set; }
        public Nullable<int> regId { get; set; }
    }
}
